#
ROOT: /data2/datasets/wenshanw/tartan_data
TYPE: tartanv1
DATASETS:
  [
    seasidetown/Data/P000,
    seasidetown/Data/P001,
    seasidetown/Data/P002,
    seasidetown/Data/P003,
    seasidetown/Data/P004,
    seasidetown/Data/P005,
    soulcity/Data/P000,
    soulcity/Data/P001,
    soulcity/Data/P002,
    soulcity/Data/P003,
    soulcity/Data/P004,
    soulcity/Data/P005,
    soulcity/Data/P006,
    soulcity/Data/P007,
    soulcity/Data/P008,
    soulcity/Data/P009,
    soulcity/Data/P010,
  ]
VO_MODEL: ./models/tartanvo_1914.pkl
POSE_MODEL: null