#
ROOT: /data2/datasets/yuhengq
TYPE: tartanv2
DATASETS:
  [
    tartanair_v2_test/Data_easy/P000,
    tartanair_v2_test/Data_easy/P001,
    tartanair_v2_test/Data_easy/P002,
    tartanair_v2_test/Data_easy/P003,
    tartanair_v2_test/Data_easy/P004,
    tartanair_v2_test/Data_easy/P005,
    tartanair_v2_test/Data_easy/P006,
    tartanair_v2_test/Data_easy/P007,
    tartanair_v2_test/Data_easy/P008,
    tartanair_v2_test/Data_easy/P009,
    tartanair_v2_test/Data_easy/P010,
    tartanair_v2_test/Data_easy/P011,
    tartanair_v2_test/Data_easy/P012,
    tartanair_v2_test/Data_easy/P013,
    tartanair_v2_test/Data_hard/P000,
    tartanair_v2_test/Data_hard/P001,
    tartanair_v2_test/Data_hard/P002,
    tartanair_v2_test/Data_hard/P003,
    tartanair_v2_test/Data_hard/P004,
    tartanair_v2_test/Data_hard/P005,
    tartanair_v2_test/Data_hard/P006,
    tartanair_v2_test/Data_hard/P007,
    tartanair_v2_test/Data_hard/P008,
    tartanair_v2_test/Data_hard/P009,
    tartanair_v2_test/Data_hard/P010,
    tartanair_v2_test/Data_hard/P011,
    tartanair_v2_test/Data_hard/P012,
    tartanair_v2_test/Data_hard/P013,
  ]
VO_MODEL: ./models/tartanvo_1914.pkl
POSE_MODEL: null